server.port=${PORT:8081}
spring.application.name=loom-backend
spring.config.import=optional:file:.env[.properties]

spring.datasource.url=${DATABASE_URL:jdbc:postgresql://db.llfcpjoysmehsrgevdof.supabase.co:5432/postgres?currentSchema=public}
spring.datasource.username=${DATABASE_USERNAME:postgres}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.properties.hibernate.default_schema=loom
spring.jpa.properties.hibernate.hbm2ddl.create_namespaces=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

application.security.jwt.secret-key=${JWT_SECRET}
app.cookie.domain=${COOKIE_DOMAIN:.arqulat.com}
app.frontend.url=${FRONTEND_URL:http://localhost:5173}
